name: Build Cross-Platform Installers

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build Windows executable
      run: |
        pyinstaller main-windows.spec --clean --noconfirm
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: assignment-tracker-windows
        path: dist/assignment-tracker.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build macOS app
      run: |
        pyinstaller main-macos.spec --clean --noconfirm
    
    - name: Create DMG (optional)
      run: |
        # Install create-dmg for making a DMG installer
        brew install create-dmg
        create-dmg \
          --volname "Assignment Tracker" \
          --window-pos 200 120 \
          --window-size 600 300 \
          --icon-size 100 \
          --icon "Assignment Tracker.app" 175 120 \
          --hide-extension "Assignment Tracker.app" \
          --app-drop-link 425 120 \
          "Assignment-Tracker-Installer.dmg" \
          "dist/"
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: assignment-tracker-macos
        path: |
          dist/Assignment Tracker.app
          Assignment-Tracker-Installer.dmg

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build Linux executable
      run: |
        pyinstaller main.spec --clean --noconfirm
    
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: assignment-tracker-linux
        path: dist/assignment-tracker/

  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          assignment-tracker-windows/assignment-tracker.exe
          assignment-tracker-macos/Assignment Tracker.app
          assignment-tracker-macos/Assignment-Tracker-Installer.dmg
          assignment-tracker-linux/assignment-tracker/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
